#  release
---
server:
  api:
    homs: http://10.20.101.197:8081

eureka:
  client:
    registryFetchIntervalSeconds: 5
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://10.20.101.48:8761/eureka

