server:
  servlet:
    context-path: /
  port: 31000
  ssl:
    enabled: false

spring:
  application:
    name: HLHDS-GATEWAY-SERVICE
  output:
    ansi.enabled: always # colorize console logs

eureka:
  instance:
    instance-id: HLHDS-GATEWAY-SERVICE
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true # actuator를 통해 circuitbraker 상태를 확인하기 위해 설정
        minimumNumberOfCalls: 5 # Circuit Breaker가 에러 비율 또 slow call 비율을 계산하기 전에 요구되는 최소한의 요청 수
        failureRateThreshold: 50  # 에러 비율 (퍼센트)로 해당 값 이상으로 에러 발생시 서킷이 Open 된다.
        waitDurationInOpenState: 10s  # 서킷의 상태가 Open에서 Half-open으로 변경되기 전에 Circuit Breaker가 기다리는 시간
    instances:
      testCircuitBreaker:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: always # actuator에서 디테일한 정보들을 확인하기 위해 설정
  health:
    circuitbreakers:
      enabled: true # actuator를 통해 circuitbraker 상태를 확인하기 위해 설정


app:
  auth:
    jwt-secret: hallahds

##################################################################################################################
# LOG4J 관련
##################################################################################################################
logging:
  level:
    sql: error
    root: info
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d %-5level %logger : %msg%n"
  logback:
    rollingpolicy:
      clean-history-on-start: false
      max-file-size: 500MB
      max-history: 10

