#  local
---
server:
  port: 31000
  db:
#    redis:
#      host: 10.20.101.99
#      port: 6379
  api:
    intf: http://localhost:34000
    intf2: http://localhost:34001
    auth: http://localhost:34009
    homs: http://localhost:8080
    adm: http://localhost:80
    mdm: http://localhost:80
    bms: http://localhost:80
    vms: http://localhost:80

spring:
#  redis:
#    host: ${server.db.redis.host}
#    port: ${server.db.redis.port}
  application:
    name: apigateway-local
management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
  endpoint:
    gateway:
      enabled: true

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
