#  release
---
server:
  api:
    intf: lb://HALLAHDS-API-SERVICE
    homs: http://10.20.101.197:8081
    adm: lb://GLOW-ADM-SERVICE
    mdm: lb://GLOW-MDM-SERVICE
    bms: lb://GLOW-BMS-SERVICE
    vms: lb://GLOW-VMS-SERVICE

eureka:
  client:
    registryFetchIntervalSeconds: 5
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://10.20.101.48:8761/eureka
