#  develop
---
server:
  db:
    redis:
      host: 10.20.101.99
      port: 6379
  api:
    erp: http://localhost:34000
    auth: http://localhost:34009
    homs: http://localhost:8080

#    wms: http://localhost:34009
#    bms: http://localhost:34009

spring:
  redis:
    host: ${server.db.redis.host}
    port: ${server.db.redis.port}
  application:
    name: apigateway-develop
  cloud:
    gateway:
      routes:
        - id: api-erp
          uri: ${server.api.erp}
          predicates:
            - Path=/api/erp/**
            - Method=POST, GET, PUT, DELETE
          filters:
            - RewritePath=/api/erp/(?<segment>.*), /$\{segment}
            - ERPFilter
        - id: api-auth
          uri: ${server.api.auth}
          predicates:
            - Path=/api/auth/**
            - Method=POST, GET
          filters:
#            - RemoveRequestHeader=Cookie
            - RewritePath=/api/auth/(?<segment>.*), /$\{segment}
#            - AddRequestHeader=second-request, second-request-header2
#            - AddResponseHeader=second-response, second-response-header2
        - id: api-homs
          uri: ${server.api.homs}
          predicates:
            - Path=/api/homs/**
            - Method=POST, GET, PUT, DELETE
          filters:
            - RewritePath=/api/homs/(?<segment>.*), /$\{segment}
management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
  endpoint:
    gateway:
      enabled: true
