#  release
---
server:
  api:
    intf: http://10.20.101.99:34000
    auth: http://10.20.101.134:34009
    homs: http://10.20.101.197:8081
#    adm: http://10.20.101.171:18081
#    mdm: http://10.20.101.171:18082
#    bms: http://10.20.101.171:18083
#    vms: http://10.20.101.171:18084
    adm: lb://ADM-SERVICE
    mdm: lb://MDM-SERVICE
    bms: lb://BMS-SERVICE
    vms: lb://VMS-SERVICE

spring:
  application:
    name: apigateway-release

eureka:
  client:
    registryFetchIntervalSeconds: 5
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://10.20.101.48:8761/eureka
