server:
  port: 31000

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: 10.20.11.101
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: api-intf
          uri: ${server.api.intf}
          predicates:
            - Path=/api/intf/**
            - Method=POST, GET, PUT
            - Weight=group_intf, 10
          filters:
            - RewritePath=/api/intf/(?<segment>.*), /$\{segment}
            - ERPFilter
#        - id: api-intf2
#          uri: ${server.api.intf2}
#          predicates:
#            - Path=/api/intf/**
#            - Method=POST, GET
#            - Weight=group_intf, 2,
#          filters:
#            - RewritePath=/api/intf/(?<segment>.*), /$\{segment}
#            - ERPFilter
        - id: api-auth
          uri: ${server.api.auth}
          predicates:
            - Path=/api/auth/**
            - Method=POST, GET
          filters:
            #            - RemoveRequestHeader=Cookie
            - RewritePath=/api/auth/(?<segment>.*), /$\{segment}
        #            - AddRequestHeader=second-request, second-request-header2
        #            - AddResponseHeader=second-response, second-response-header2
        - id: api-homs
          uri: ${server.api.homs}
          predicates:
            - Path=/api/homs/**
            - Method=POST, GET, PUT, DELETE
          filters:
            - RewritePath=/api/homs/(?<segment>.*), /$\{segment}
        # adm service
        - id: api-adm
          uri: ${server.api.adm}
          predicates:
            - Path=/api/adm/**
            - Method=POST, GET, PUT, DELETE, OPTIONS
          filters:
            - RewritePath=/api/adm/(?<segment>.*), /adm/$\{segment}
            - GlobalFilter
        # mdm service
        - id: api-mdm
          uri: ${server.api.mdm}
          predicates:
            - Path=/api/mdm/**
            - Method=POST, GET, PUT, DELETE, OPTIONS
          filters:
            - RewritePath=/api/mdm/(?<segment>.*), /mdm/$\{segment}
        # bms service
        - id: api-bms
          uri: ${server.api.bms}
          predicates:
            - Path=/api/bms/**
            - Method=POST, GET, PUT, DELETE, OPTIONS
          filters:
            - RewritePath=/api/bms/(?<segment>.*), /bms/$\{segment}
        # vms service
        - id: api-vms
          uri: ${server.api.vms}
          predicates:
            - Path=/api/vms/**
            - Method=POST, GET, PUT, DELETE, OPTIONS
          filters:
            - RewritePath=/api/vms/(?<segment>.*), /vms/$\{segment}

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - $systemver
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
            maxAge: 1728000
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Gateway GlobalFilter
            preLogger: true
            postLogger: true
      httpclient:
        max-header-size: 52428800

#  redis:
#    jedis.pool.max-active: 10000
#    jedis.pool.max-idle: 50
#    jedis.pool.max-wait: -1
#    jedis.pool.min-idle: 0
#    timeout: 1

jwt.secret: hallahds
secret:
  salt:
    key: hallahdstest

##################################################################################################################
# LOG4J 관련
##################################################################################################################
logging:
  level:
    sql: error
    root: info
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d %-5level %logger : %msg%n"
  logback:
    rollingpolicy:
      clean-history-on-start: false
      max-file-size: 500MB
      max-history: 10

