#  develop
---
server:
  port: 31000
  db:
#    redis:
#      host: 10.20.101.99
#      port: 6379
  api:
    intf: http://10.20.101.99:34000
    auth: http://10.20.101.99:34009
    homs: http://10.20.101.171:8080
    adm: http://10.20.101.171:18081
    mdm: http://10.20.101.171:18082
    bms: http://10.20.101.171:18083
    vms: http://10.20.101.171:18084


spring:
#  redis:
#    host: ${server.db.redis.host}
#    port: ${server.db.redis.port}
  application:
    name: apigateway-develop
