#  release
---
server:
  api:
    intf: lb://HALLAHDS-API-SERVICE
    homs: http://10.20.101.197:8081
    adm: lb://HGLOW-ADM-SERVICE
    mdm: lb://HGLOW-MDM-SERVICE
    bms: lb://HGLOW-BMS-SERVICE
    vms: lb://HGLOW-VMS-SERVICE

spring:
  application:
    name: apigateway-release

eureka:
  client:
    registryFetchIntervalSeconds: 5
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://10.20.101.48:8761/eureka
