#  release
---
server:
  db:
#    redis:
#      host: 10.20.101.134
#      port: 6379
  api:
    intf: http://10.20.101.99:34000
    auth: http://10.20.101.134:34009
    homs: http://10.20.101.197:8081
#    wms: http://10.20.101.99:34009
#    bms: http://10.20.101.99:34009

spring:
#  redis:
#    host: ${server.db.redis.host}
#    port: ${server.db.redis.port}
  application:
    name: apigateway-release
