springdoc:
  enable-native-support: true
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /api/v3/api-docs
        name: HALLAHDS-API-SERVICE
        primaryName: HALLAHDS-API-SERVICE

      - url: /api/sdp/adm/v3/api-docs
        name: HL-WMS-API-ADM
        primaryName: HL-WMS-API-ADM
      - url: /api/sdp/mdm/v3/api-docs
        name: HL-WMS-API-MDM
        primaryName: HL-WMS-API-MDM
      - url: /api/sdp/wms/v3/api-docs
        name: HL-WMS-API-WMS
        primaryName: HL-WMS-API-WMS
      - url: /api/sdp/oms/v3/api-docs
        name: HL-WMS-API-OMS
        primaryName: HL-WMS-API-OMS
      - url: /api/sdp/tms/v3/api-docs
        name: HL-WMS-API-TMS
        primaryName: HL-WMS-API-TMS
      - url: /api/sdp/wms-t/v3/api-docs
        name: HL-WMS-API-TACTIC
        primaryName: HL-WMS-API-TACTIC


openapi:
  service:
    title: HL-API-Swagger doc #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://localhost:31000 #api gateway url
