#  develop
---
server:
  db:
#    redis:
#      host: 10.20.101.99
#      port: 6379
  api:
    intf: http://10.20.101.99:34000
    auth: http://10.20.101.99:34009
    homs: http://10.20.101.171:8080
    adm: http://10.20.101.171:18081
    mdm: http://10.20.101.171:18082
    bms: http://10.20.101.171:18083
    vms: http://10.20.101.171:18084


spring:
#  redis:
#    host: ${server.db.redis.host}
#    port: ${server.db.redis.port}
  application:
    name: apigateway-develop
  cloud:
    gateway:
      routes:
        - id: api-intf
          uri: ${server.api.intf}
          predicates:
            - Path=/api/intf/**
            - Method=POST, GET, PUT, DELETE
          filters:
            - RewritePath=/api/intf/(?<segment>.*), /$\{segment}
            - ERPFilter

        - id: api-auth
          uri: ${server.api.auth}
          predicates:
            - Path=/api/auth/**
            - Method=POST, GET
          filters:
#            - RemoveRequestHeader=Cookie
            - RewritePath=/api/auth/(?<segment>.*), /$\{segment}
#            - AddRequestHeader=second-request, second-request-header2
#            - AddResponseHeader=second-response, second-response-header2

        - id: api-homs
          uri: ${server.api.homs}
          predicates:
            - Path=/api/homs/**
            - Method=POST, GET, PUT, DELETE
          filters:
            - RewritePath=/api/homs/(?<segment>.*), /$\{segment}
#            - HOMSFilter
# adm service
        - id: api-adm
          uri: ${server.api.adm}
          predicates:
            - Path=/api/adm/**
            - Method=POST, GET, PUT, DELETE, OPTIONS
          filters:
            - RewritePath=/api/adm/(?<segment>.*), /adm/$\{segment}
# mdm service
        - id: api-mdm
          uri: ${server.api.mdm}
          predicates:
            - Path=/api/mdm/**
            - Method=POST, GET, PUT, DELETE, OPTIONS
          filters:
            - RewritePath=/api/mdm/(?<segment>.*), /mdm/$\{segment}
# bms service
        - id: api-bms
          uri: ${server.api.bms}
          predicates:
            - Path=/api/bms/**
            - Method=POST, GET, PUT, DELETE, OPTIONS
          filters:
            - RewritePath=/api/bms/(?<segment>.*), /bms/$\{segment}
# vms service
        - id: api-vms
          uri: ${server.api.vms}
          predicates:
            - Path=/api/vms/**
            - Method=POST, GET, PUT, DELETE, OPTIONS
          filters:
            - RewritePath=/api/vms/(?<segment>.*), /vms/$\{segment}
management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
  endpoint:
    gateway:
      enabled: true

#eureka:
#  instance:
#    hostname: 10.20.101.99
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
