#  local
---
server:
  api:
    homs: http://localhost:8080

app:
  host:
    allowed:
      - 10.20.101.171     # homs
      - 10.20.101.171     # glow
      - 10.20.254.22     # LJW
      - 10.20.11.101     # MSH

eureka:
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

