#  develop-db
---
server:
  db:
    redis:
      host: 10.20.101.134
      port: 6379
  api:
    erp: http://10.20.101.133:34000
    auth: http://10.20.101.134:34009
    homs: http://10.20.101.197:8081
#    wms: http://10.20.101.99:34009
#    bms: http://10.20.101.99:34009

spring:
  redis:
    host: ${server.db.redis.host}
    port: ${server.db.redis.port}
  application:
    name: apigateway-develop
  cloud:
    gateway:
      routes:
        - id: api-erp
          uri: ${server.api.erp}
          predicates:
            - Path=/api/erp/**
          filters:
            - RewritePath=/api/erp/(?<segment>.*), /$\{segment}
            - ERPFilter
        - id: api-auth
          uri: ${server.api.auth}
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /$\{segment}
#            - AddRequestHeader=second-request, second-request-header2
#            - AddResponseHeader=second-response, second-response-header2

#eureka:
#  instance:
#    hostname: 10.20.101.134
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
