spring:
  profiles:
    group:
      "local" : "localhost, default"
---
spring:
  profiles:
    group:
      "develop": "develop, default"
---
spring:
  profiles:
    group:
      "release" : "release, default"
