#  develop
---
server:
  api:
    intf: http://10.20.101.99:34000
    auth: http://10.20.101.99:34009
    homs: http://10.20.101.171:8080
    adm: http://10.20.101.171:18081
    mdm: http://10.20.101.171:18082
    bms: http://10.20.101.171:18083
    vms: http://10.20.101.171:18084

spring:
  application:
    name: apigateway-develop

eureka:
  client:
    registryFetchIntervalSeconds: 5
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://10.20.101.99:8761/eureka
