#  release
---
server:
  api:
    homs: http://10.20.101.197:8081

app:
  host:
    allowed:
      - 10.20.101.194 # homs
      - 10.20.101.195 # homs
      - 10.20.101.196 # homs batch
      - 10.20.101.83 # glow
      - 10.20.101.84 # glow
      - 10.20.101.97 # glow batch
  allowedAddress:
    - "0.0.0.0"
    - "0:0:0:0"
    - "10.110."
    - "10.20."
    - "175.207."
    - "172.20."

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

eureka:
  client:
    registryFetchIntervalSeconds: 5
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://10.20.101.48:8761/eureka

