#  local
---
server:
  api:
    homs: http://localhost:8080
#    adm: http://10.20.101.171:18081
#    mdm: http://10.20.101.171:18082
#    bms: http://10.20.101.171:18083
#    vms: http://10.20.101.171:18084


eureka:
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    sql: error
    root: info
