#  develop
---
server:
  api:
    homs: http://10.20.101.171:8080

app:
  host:
    allowed:
      - 10.20.101.171     # homs
      - 10.20.101.171     # glow
      - 10.20.254         # VPN
      - 10.20.11.101     # MSH
  allowedAddress:
    - "127.0.0.1"
    - "0.0.0.0"
    - "0:0:0:0"
    - "10.110."
    - "10.20."
    - "175.207."
    - "172.20."


springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

eureka:
  client:
    registryFetchIntervalSeconds: 5
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://10.20.101.99:8761/eureka

