spring:
  profiles:
    group:
      "local" : "local, default, swagger, route"
---
spring:
  profiles:
    group:
      "develop": "develop, default, swagger, route"
---
spring:
  profiles:
    group:
      "release" : "release, default, swagger, route"
